default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['SPUTNIK_DEVELOPMENT_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['SPUTNIK_DATABASE_USERNAME'] %>
  password: <%= ENV['SPUTNIK_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['SPUTNIK_TEST_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['SPUTNIK_DATABASE_USERNAME'] %>
  password: <%= ENV['SPUTNIK_DATABASE_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 15
  database: <%= ENV['SPUTNIK_PROD_DATABASE_NAME'] %>
  username: <%= ENV['SPUTNIK_DATABASE_USERNAME'] %>
  password: <%= ENV['SPUTNIK_DATABASE_PASSWORD'] %>